packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.14.0
    '@types/node': ^22.18.10
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.37.0
    glob: ^11.0.3
    prettier: ^3.7.4
    typescript: ^5.9.3
    vitest: ^3.2.4
    tsdown: ^0.15.8
